volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  postgres:
    image: postgres:13.10
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/

  kitty_backend:
    image: clarkefeed/kittygram_backend:latest
    env_file: .env
    restart: always
    depends_on:
      - postgres
    volumes:
      - static:/app/collected_static/
      - media:/app/media/    

  kitty_frontend:
    image: clarkefeed/kittygram_frontend:latest
    env_file: .env
    restart: always
    volumes:
      - frontend_build:/app/build/
  
  kitty_gateway:
    image: clarkefeed/kittygram_gateway:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - frontend_build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - kitty_backend
      - kitty_frontend