name: CI/CD for Kittygram

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Check PEP8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: |
          pip install flake8

      - name: Test with flake8
        run: |
          flake8 --ignore=E123,E301,E302,E501,W291,W292,W293,F401 .

  build:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend:latest frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend:latest

      - name: Build and push gateway image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest nginx
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest

  deploy:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Копируем docker-compose.production.yml на продакшен-сервер:
      - name: Copy docker-compose.yml via ssh
        uses: appleboy/scp-action@master
      # Передаём параметры для action appleboy/scp-action:
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.production.yml"
          target: "/home/clarke/kittygram/"
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # Параметр script передаёт в action appleboy/ssh-action команды,
          # которые нужно выполнить на сервере, 
          # с которым установлено соединение:
          script: |
            cd /home/clarke/kittygram/
            sudo docker compose -f docker-compose.production.yml pull
            sudo docker compose -f docker-compose.production.yml down
            sudo docker compose -f docker-compose.production.yml up -d
            sudo docker compose -f docker-compose.production.yml exec kitty_backend python manage.py migrate
            sudo docker compose -f docker-compose.production.yml exec kitty_backend python manage.py collectstatic --noinput

  auto_tests:
    name: Run Auto Tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest pyyaml requests
      
      - name: Run backend tests
        run: |
          pytest

  notify_in_telegram:
    name: Notify in Telegram
    runs-on: ubuntu-latest
    needs: auto_tests
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Kittygram version successfully passed auto-tests and has been deployed! Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"